# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e5cc28cc5d1baa54f3f46fb865cf2172650a3d9856543aa381da1ce065b4efdaffbcadd22a69a46953bb407625724d122558e0d5f0f40ee2a1ba7a12dffbcd

test:
  secret_key_base: 8269925e6a985d2f2d42071913c7cd4536943706b7446c52c9fe368529111a8fb1a4afed5150b14420de9486a518c6ffb7e0f5e64e1d851575fc284c376747a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
